apiVersion: v1
kind: Service
metadata:
  name: svelte-web
  namespace: task-platform-apps
  labels:
    app: svelte-web
spec:
  type: ClusterIP
  selector:
    app: svelte-web
  ports:
    - name: http
      port: 4003
      targetPort: 4003
