apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-gateway-config
  namespace: task-platform-apps
data:
  NODE_ENV: "production"
  APP_VERSION: "1.0.0"
  HTTP_PORT: "4002"
  # gRPC endpoints of backend services
  AUTH_SERVICE_GRPC_URL: "auth-service.task-platform-apps.svc.cluster.local:5000"
  TASK_SERVICE_GRPC_URL: "task-service.task-platform-apps.svc.cluster.local:5001"
  ANALYTICS_SERVICE_GRPC_URL: "analytics-service.task-platform-apps.svc.cluster.local:5005"
  FILE_SERVICE_GRPC_URL: "file-service.task-platform-apps.svc.cluster.local:50046"
  # Token settings
  ACCESS_TOKEN_EXPIRES_IN: "15m"
  REFRESH_TOKEN_EXPIRES_IN: "7d"
  # Cookie settings
  AUTH_SECURE_COOKIES: "false"
  # CORS
  CLIENT_URL: "http://task-platform.local"
