apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: task-platform-apps
data:
  NODE_ENV: "production"
  APP_VERSION: "1.0.0"
  HTTP_PORT: "4004"
  # Pulsar endpoint
  PULSAR_SERVICE_URL: "pulsar://pulsar.task-platform-infra.svc.cluster.local:6650"
  # Redis endpoint for Socket.IO adapter and user-socket mapping
  REDIS_URL: "redis://redis.task-platform-infra.svc.cluster.local:6379"
  # CORS
  CLIENT_URL: "http://task-platform.local"
