apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
  namespace: task-platform-apps
data:
  NODE_ENV: "production"
  APP_VERSION: "1.0.0"
  HTTP_PORT: "4001"
  GRPC_PORT: "5001"
  # Auth Service gRPC endpoint
  AUTH_SERVICE_GRPC_URL: "auth-service.task-platform-apps.svc.cluster.local:5000"
  # Pulsar endpoint
  PULSAR_SERVICE_URL: "pulsar://pulsar.task-platform-infra.svc.cluster.local:6650"
