apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: task-platform-apps
data:
  NODE_ENV: "production"
  APP_VERSION: "1.0.0"
  HTTP_PORT: "4005"
  GRPC_PORT: "5005"
  PULSAR_SERVICE_URL: "pulsar://pulsar.task-platform-infra.svc.cluster.local:6650"
