apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: task-platform-apps
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 4005
      targetPort: 4005
    - name: grpc
      port: 5005
      targetPort: 5005
